# Generated by Django 3.2.16 on 2022-12-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20221212_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
    ]
